### ISSUE TITLE
Linux port / NoCombine

### ISSUE THREAD

**Issue by helje5** [swiftwebui/SwiftWebUI#11]
To run things on Linux we only really need a tiny subset of Combine, and the types for that are already prepared in Misc/NoCombine.swift.

We just need a way to track the sinks attached to a PassthroughSubject.

P.S.: A Swift 5.1 container would be also required of course.

**Comment by linqingmo** [comment]
Will OpenCombine help? [OpenCombine](https://github.com/broadwaylamb/OpenCombine.git)

**Comment by helje5** [comment]
Possibly!

**Comment by SpectralDragon** [comment]
OpenCombine will nice alternative instead of the native framework!

**Comment by helje5** [comment]
If someone wants to give it a try, go ahead!

Things are now building OK on Linux, but some things won't work (e.g. the Navigation in AvocadoToast) because Combine is not available.

**Comment by helje5** [comment]
I created an OpenCombine branch, which at least compiles. Unfortunately OpenCombine is not yet tagged in any way and we don't want no branch deps :-)

**Comment by broadwaylamb** [comment]
I can create a tag for you.

**Comment by helje5** [comment]
No, w/ semantic versioning 0.1.0 should be fine, no alpha needed. Don't forget the included branched deps.

**Comment by broadwaylamb** [comment]
The `alpha` thing combined with zero major version is to emphasize that this is very-very early in developent not intended to be used in production :)

**Comment by helje5** [comment]
That's what 0.1.0 is good for. If that is still too much, use 0.0.1 :-)

**Comment by broadwaylamb** [comment]
Okay, went with 0.1.0.

https://github.com/broadwaylamb/OpenCombine/releases/tag/0.1.0

**Comment by helje5** [comment]
Very well, it's in and working! https://github.com/swiftwebui/SwiftWebUI/releases/tag/0.1.7
