### ISSUE TITLE
Add Examples folder

### ISSUE THREAD

**Issue by lolgear** [swiftwebui/SwiftWebUI#25]
I would like to gitcloning and get examples :)

Thanks!

**Comment by helje5** [comment]
A problem w/ embedded example folders is that everyone adding the library as a dependency has to download the samples too. But maybe it's still worth it.

**Comment by mattt** [comment]
+1 for more examples, but -1 for embedded them in a subdirectory of this repository.

@helje5 Since you own the @SwiftWebUI organization, you have a nice built-in way to keep examples separate but still within a cohesive namespace. Each example app should be self-contained and deployable on its own, building from the main SwiftWebUI project as a dependency.

**Comment by helje5** [comment]
Well, yes, that is the current setup :-) I think it's OK. BTW: Another great example app might be a port of that Movies SwiftUI app that circled around a week ago.

**Comment by unnamedd** [comment]
@helje5 yesterday I tried your examples, but I avoided to use the Xcode. I recreated a simple structure using SwiftPM and moved your example files into it. If you want, I can do again and send you as a PR. Make sense to you?

_Why I did that?_
For some reason, the SPM integration on Xcode isn't working well yet. My credentials are configured, but every time when I try to refresh the package dependencies, Xcode ask me to do the process again. (login, 2fa and so on)

**Comment by helje5** [comment]
I've added an SPM manifest for AvocadoToast in the Linux branch already (and adjusted the file structure for SPM), probably going to do the same for Tinker2. So I suppose I don't need this particular PR :-) But thanks for the offer!

**Comment by unnamedd** [comment]
Awesome @helje5! Thanks for the quick answer!

**Comment by helje5** [comment]
OK, they all have SPM manifests now. I also added the minimal HelloWorld to the main project.

I guess I close this for now. That more examples are cool should be obvious :-)
