### ISSUE TITLE
Sample Example Run Xcode Beta3 Run Error?

### ISSUE THREAD

**Issue by josercc** [swiftwebui/SwiftWebUI#35]
dyld: Symbol not found: _$s7Combine11SubscribersO4SinkCy_xq_GAA11CancellableAAMc
  Referenced from: /Users/zhangxing/Library/Developer/Xcode/DerivedData/Tinker2-cxubagqiogijkfhczskwfdfwlmmb/Build/Products/Debug/Tinker2
  Expected in: /System/Library/Frameworks/Combine.framework/Versions/A/Combine
 in /Users/zhangxing/Library/Developer/Xcode/DerivedData/Tinker2-cxubagqiogijkfhczskwfdfwlmmb/Build/Products/Debug/Tinker2

**Comment by josercc** [comment]
sample code this
```swift
struct MainPage : View {
    var body: some View {
        HStack {
            Text("Hello")
            Text("Word")
        }
    }
}
```

**Comment by helje5** [comment]
You are combining Xcode b3 w/ Catalina b1 or b2, that's doesn't fly. Runtimes need to match. "ABI"
