### ISSUE TITLE
 Reference Swift WebUI

### ISSUE THREAD

**Issue by josercc** [swiftwebui/SwiftWebUI#38]
I want to write a SwiftKitUI using the system's UIKit and AppKit support for the low version. But I don't know how to write it. I don't know if I can read it according to the source code of SwiftWebUI.

**Comment by helje5** [comment]
Sorry, I don't understand your question. Could you try to rephrase it?

**Comment by josercc** [comment]
@helje5 Because Apple's SwiftUI does not support low versions. I want to make a compatible library that is packaged like Apple's SwiftUI. In fact, I also want to contribute to SwiftWebUI, but I will not develop it myself. I think some of the core code of SwiftWebUI can be borrowed from the library I developed. And there are still Swift grammar questions that need to be consulted. Thank you in advance if you can help me.
[SwiftKitUI](https://github.com/swiftkitui/SwiftKitUI)

**Comment by helje5** [comment]
Still no idea what you actually want as part of this issue. Good luck w/ your SwiftKitUI!
