### ISSUE TITLE
Review SessionID Security

### ISSUE THREAD

**Issue by helje5** [swiftwebui/SwiftWebUI#4]
The way session IDs are generated is probably not status quo. Security experts please ;-)

**Comment by mattt** [comment]
I'm not a security expert, but reading [the current implementation](https://github.com/swiftwebui/SwiftWebUI/blob/e8bb09e52124711460e0a6d44b2a23ba17883ac6/Sources/SwiftWebUI/ViewHosting/NIOSessionIDGeneration.swift#L19-L31), I think the small number of random bits (2<sup>10</sup> for 1337 + 2<sup>64</sup> for random `Int`) is problematic. The addition of a timestamp doesn't really do much to mitigate an attack and [MD5 isn't cryptographically secure](https://en.wikipedia.org/wiki/MD5#Security).

The simplest replacement with more reasonable security is to use Foundation `UUID`, whose values are generated on macOS and Linux from 122 random bits read from `/dev/urandom` (+6 fixed bits for UUIDv4 format) [[1]](https://github.com/apple/swift-corelibs-foundation/blob/a66fe709f33cda3003c3432284504543bc8c3d30/Foundation/UUID.swift#L25-L31),[[2]](https://github.com/apple/swift-corelibs-foundation/blob/e12c2d8af7f71be978b3969e13205ed067ffb733/uuid/uuid.c#L156-L163), [[3]](https://github.com/apple/swift-corelibs-foundation/blob/e12c2d8af7f71be978b3969e13205ed067ffb733/uuid/uuid.c#L92-L96).

Here's what this would look like:

```swift
import struct Foundation.UUID

extension NIOHostingSession {
  
  // MARK: - Session ID
    
  static func createSessionID() -> String {
    return UUID().uuidString
  }
}
```

However, something to consider: According to [this article](https://neilmadden.blog/2018/08/30/moving-away-from-uuids/), a motivated attacker may compromise 122 random bits in under an hour, so UUID isn't suitable for most production environments. As an alternative, the article suggests Base64-encoding 160 random bits. I'm not familiar with the current best-practices for cross-platform generation of random data in Swift, but I'd be happy to investigate and submit a PR if that's something you'd be interested in.

**Comment by helje5** [comment]
OK, did the UUID thing, much better, thanks.

I'm still interested in the current best practices, but only mildly :-) So for now I keep that open just in case someone else has extra suggestions.

BTW: We could also couple a session to a WebSocket connection, i.e. use no session-id at all. Though that would forbid reconnects, though we could use rolling reconnect-ids for that. I suppose.
