### ISSUE TITLE
Potential issues with `Binding` creation

### ISSUE THREAD

**Issue by DevAndArtist** [swiftwebui/SwiftWebUI#41]
Hi @helje5 I just re-watched this WWDC talk: https://developer.apple.com/videos/play/wwdc2019/226/ 

At around 33:00 the speaker says that `Binding` does not capture references.

I tested it with `BindableObject`'s subscript to verify the behavior.

```swift
public struct _Binding<Value> {
  private let _getter: () -> Value
  private let _setter: (Value) -> Void
  
  public var wrappedValue: Value {
    get {
      return _getter()
    }
    nonmutating set {
      _setter(newValue)
    }
  }
  
  public init(
    getValue getter: @escaping () -> Value,
    setValue setter: @escaping (Value) -> Void
  ) {
    _getter = getter
    _setter = setter
  }
}

class VM: BindableObject {
  let willChange = PassthroughSubject<Void, Never>()
  var value = ""
  
  public func getBinding<Subject>(
    keyPath path: ReferenceWritableKeyPath<VM, Subject>
  ) -> _Binding<Subject> {
    return _Binding(
      getValue: {
        self[keyPath: path]
      },
      setValue: { newValue in
        self[keyPath: path] = newValue
      }
    )
  }
}

var vm: VM = VM()
print(CFGetRetainCount(vm)) // 2
let biding_1: Binding<String> = vm[\.value]
print(CFGetRetainCount(vm)) // 3 - captures the reference once.
let biding_2 = vm.getBinding(keyPath: \.value)
print(CFGetRetainCount(vm)) // 5 🐞 - captures the reference twice.
```

You have similar code here:

https://github.com/swiftwebui/SwiftWebUI/blob/develop/Sources/SwiftWebUI/Properties/BindableObject.swift#L28

I suspect that they do use `[unowned self]` in one of the closures because the other closure is already known to capture the reference and it's not needed to do it twice. I think in case of the custom `_Binding` type from the example I would put it into the getter closure because it should be destroyed at first (I assume the top to bottom deallocation order here).

**Comment by helje5** [comment]
> At around 33:00 the speaker says that Binding does not capture references

Didn't find that. Can you give a more specific time? I think a Binding must reference the source strongly, after all it can be passed around at will?

**Comment by DevAndArtist** [comment]
> By using the Binding Property Wrapper, you define an explicit dependency to a source of truth *without owning it*.

My point is that it should be enough to capture the strong reference just once from a single closure, not from both. Apple seems to be doing the same thing. The Implementation in this repo will create two strong references. 

I don't think it would hurt not doing that. I'm just saying that I noticed that behavior.

So this should do the trick:

```
 return Binding(
   // Don't capture a strong ref here.
   getValue: { [unowned self] in
     self[keyPath: path]
   },
   // We will capture it here once.
   setValue: { newValue in
     self[keyPath: path] = newValue
   }
 )
```

**Comment by helje5** [comment]
Ah OK, so it’s not a potential issue, just a minor performance disadvantage.
