### ISSUE TITLE
No

### ISSUE THREAD

**Issue by yordis** [SwiftWebUI/SwiftWebUI#45]
> To repeat the disclaimer: This is a toy project! Do not use it for production. Use it to learn more about SwiftUI and its inner workings.

![image](https://user-images.githubusercontent.com/4237280/66371528-3d848680-e958-11e9-8ee0-8a88a3d6d7a2.png)

No, make it production-ready 😂😂😂😂

No seriously, I need this in my life after a decade of HTML/CSS/JS 😭 I hope this project brings new perspective to the ecosystem.

Cheers, and thank you for putting together this project.

**Comment by helje5** [comment]
First we need a working Swift for WASM.
