### ISSUE TITLE
How to publish the binary product to a hosting service?

### ISSUE THREAD

**Issue by ApostolisApo** [SwiftWebUI/SwiftWebUI#54]
Hi, 

I am really impressed with the framework! I tested some syntaxes and they work flawlessly.

However  I am wondering if I can really use for publishing my personal website this way...

How can I host the resulting SwiftWebUI binary to e.g. WordPress or AWS?

I am asking this because I see that Wordpress requires HTML files (which I could not find inside the project) and AWS offers no MacOS instances (??)

**Comment by helje5** [comment]
> Disclaimer: This is a toy project! Do not use for production. Use it to learn more about SwiftUI and its inner workings.

The answer is no, sorry :-)

P.S.: SwiftWebUI does build on Linux, but you still wouldn't want to do this.

**Comment by nidegen** [comment]
@ApostolisApo just run it on a server. need root access;)
