### ISSUE TITLE
No available targets are compatible with triple

### ISSUE THREAD

**Issue by Albahrani1995** [SwiftWebUI/SwiftWebUI#59]
hello,
so I want to try this library to see if I can make apps with it.
but when I try the steps in https://github.com/carson-katri/swiftwebui-scripts, I get error when running the command (make), and I get the following error :
cd testingAppweUI && \
	swift build --triple wasm32-unknown-wasi && \
	cp .build/debug/testingAppweUI ../dist/SwiftWASM.wasm && \
	wasm-strip ../dist/SwiftWASM.wasm && \
	gzip ../dist/SwiftWASM.wasm --best
Fetching https://github.com/carson-katri/SwiftWebUI
Fetching https://github.com/MaxDesiatov/Runtime
Fetching https://github.com/kateinoigakukun/JavaScriptKit
Cloning https://github.com/kateinoigakukun/JavaScriptKit
Resolving https://github.com/kateinoigakukun/JavaScriptKit at 1edcf70
Cloning https://github.com/MaxDesiatov/Runtime
Resolving https://github.com/MaxDesiatov/Runtime at wasi-build
Cloning https://github.com/carson-katri/SwiftWebUI
Resolving https://github.com/carson-katri/SwiftWebUI at develop
error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-wasi"'
error: unable to create target: 'No available targets are compatible with triple "wasm32-unknown-wasi"'
1 error generated.
1 error generated.
[0/7] Compiling _CJavaScriptKit dummy.c
make: *** [build] Error 1

thank you for making this

**Comment by curveddesign** [comment]
The Makefile is for a kludge Docker container build?   Are you trying to create a deployable docker container?

I just use Xcode 12.   Create a MacOS Tool project.  Import the Swift package.   Then hit the Build button in Xcode.

https://www.alwaysrightinstitute.com/swiftwebui/

**Comment by helje5** [comment]
> to see if I can make apps with it

No, you can't.

To repeat the very front page:
> Disclaimer: This is a toy project! Do not use for production. Use it to learn more about SwiftUI and its inner workings

**Comment by helje5** [comment]
If you are interested in Wasm, you might want to checkout this one: https://github.com/TokamakUI/Tokamak

**Comment by Albahrani1995** [comment]
ok, thank you for your help.
