### ISSUE TITLE
How Can I Access to Screen Size?

### ISSUE THREAD

**Issue by kadir-ince** [SwiftWebUI/SwiftWebUI#60]
How can i access to screen width and height for frame? <br>
<img width="1161" alt="Screen Shot 2020-09-30 at 10 44 06" src="https://user-images.githubusercontent.com/52853427/94657300-ec5c6800-0309-11eb-83a6-15a6c50c51e1.png">

**Comment by MaxDesiatov** [comment]
Hi @kadir-ince, thank you for reporting this issue! Unfortunately, UIKit is a closed-source framework, so no parts of it can run in browsers to get the size of your browser screen. You could try [`GeometryReader`](http://developer.apple.com/reference/swiftui/geometryreader), but it isn't supported in SwiftWebUI as far as I'm aware. We do support it in [Tokamak](https://github.com/TokamakUI/Tokamak) which runs purely in the browser.

**Comment by helje5** [comment]
Right, Geometry Reader is not supported. 

Not quite sure what the expectation is when setting the frame. Do you expect the browser window to resize?

**Comment by kadir-ince** [comment]
like as:
.frame(width: screen.width / 2)
I expect access to any item width and height size. 
```swift
Text("Hello")
     .frame(width: screen.width / 2) 
```
👇🏼👇🏼
```css
p { 
  width: 50%;
}
```
