### ISSUE TITLE
"You might be able to run SwiftWebUI within an iOS app." How might one go about this?

### ISSUE THREAD

**Issue by Jonovono** [SwiftWebUI/SwiftWebUI#63]
Curious to try this project out. Has anyone had luck getting it to run inside a iOS app? Would you render it inside a WebView? Any help would be great, thanks!

**Comment by helje5** [comment]
Why do you want to run in inside of an iOS app? Don't. iOS has the actual SwiftUI, use that! And yes, you'd use a WKWebView.

**Comment by Jonovono** [comment]
> Why do you want to run in inside of an iOS app? Don't. iOS has the actual SwiftUI, use that! And yes, you'd use a WKWebView.

Because i'm an absolute madman. Thanks
