### ISSUE TITLE
Cannot run SwiftWebUI on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by jaswch** [SwiftWebUI/SwiftWebUI#66]
I created a swift project which will display "Hello World" on a web page using SwiftWebUI. When I build my project using ```swift build``` I get this error ```'MyApp' /home/pi/MyApp: error: Error Domain=NSCocoaErrorDomain Code=260 "The file doesn’t exist."```.
I'm using Raspberry Pi Zero W running Raspberry Pi OS buster (Linux Kernel 5.10.103+ armv6l) using Swift version 5.1.5

**Comment by helje5** [comment]
The Package.swift of SwiftWebUI has a minimum Swift requirement of Swift 5.5: https://github.com/SwiftWebUI/SwiftWebUI/blob/0b248169c095959db006df60cb9041a17d29743f/Package.swift#L1

Though I'm not sure whether this is actually a hard requirement.
